/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersLoginRouteImport } from './routes/users/$login'
import { Route as TournamentsCreateRouteImport } from './routes/tournaments/create'
import { Route as TournamentsIdRouteImport } from './routes/tournaments/$id'
import { Route as MatchesIdRouteImport } from './routes/matches/$id'
import { Route as TournamentsIdOrganizerRouteImport } from './routes/tournaments/$id.organizer'
import { Route as TournamentsIdBracketRouteImport } from './routes/tournaments/$id.bracket'
import { Route as TournamentsIdGroupsGroupIdRouteImport } from './routes/tournaments/$id.groups.$groupId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersLoginRoute = UsersLoginRouteImport.update({
  id: '/users/$login',
  path: '/users/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsCreateRoute = TournamentsCreateRouteImport.update({
  id: '/tournaments/create',
  path: '/tournaments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdOrganizerRoute = TournamentsIdOrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => TournamentsIdRoute,
} as any)
const TournamentsIdBracketRoute = TournamentsIdBracketRouteImport.update({
  id: '/bracket',
  path: '/bracket',
  getParentRoute: () => TournamentsIdRoute,
} as any)
const TournamentsIdGroupsGroupIdRoute =
  TournamentsIdGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => TournamentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/profile': typeof ProfileRoute
  '/matches/$id': typeof MatchesIdRoute
  '/tournaments/$id': typeof TournamentsIdRouteWithChildren
  '/tournaments/create': typeof TournamentsCreateRoute
  '/users/$login': typeof UsersLoginRoute
  '/tournaments/$id/bracket': typeof TournamentsIdBracketRoute
  '/tournaments/$id/organizer': typeof TournamentsIdOrganizerRoute
  '/tournaments/$id/groups/$groupId': typeof TournamentsIdGroupsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/profile': typeof ProfileRoute
  '/matches/$id': typeof MatchesIdRoute
  '/tournaments/$id': typeof TournamentsIdRouteWithChildren
  '/tournaments/create': typeof TournamentsCreateRoute
  '/users/$login': typeof UsersLoginRoute
  '/tournaments/$id/bracket': typeof TournamentsIdBracketRoute
  '/tournaments/$id/organizer': typeof TournamentsIdOrganizerRoute
  '/tournaments/$id/groups/$groupId': typeof TournamentsIdGroupsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/profile': typeof ProfileRoute
  '/matches/$id': typeof MatchesIdRoute
  '/tournaments/$id': typeof TournamentsIdRouteWithChildren
  '/tournaments/create': typeof TournamentsCreateRoute
  '/users/$login': typeof UsersLoginRoute
  '/tournaments/$id/bracket': typeof TournamentsIdBracketRoute
  '/tournaments/$id/organizer': typeof TournamentsIdOrganizerRoute
  '/tournaments/$id/groups/$groupId': typeof TournamentsIdGroupsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/profile'
    | '/matches/$id'
    | '/tournaments/$id'
    | '/tournaments/create'
    | '/users/$login'
    | '/tournaments/$id/bracket'
    | '/tournaments/$id/organizer'
    | '/tournaments/$id/groups/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/profile'
    | '/matches/$id'
    | '/tournaments/$id'
    | '/tournaments/create'
    | '/users/$login'
    | '/tournaments/$id/bracket'
    | '/tournaments/$id/organizer'
    | '/tournaments/$id/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/profile'
    | '/matches/$id'
    | '/tournaments/$id'
    | '/tournaments/create'
    | '/users/$login'
    | '/tournaments/$id/bracket'
    | '/tournaments/$id/organizer'
    | '/tournaments/$id/groups/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ProfileRoute: typeof ProfileRoute
  MatchesIdRoute: typeof MatchesIdRoute
  TournamentsIdRoute: typeof TournamentsIdRouteWithChildren
  TournamentsCreateRoute: typeof TournamentsCreateRoute
  UsersLoginRoute: typeof UsersLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$login': {
      id: '/users/$login'
      path: '/users/$login'
      fullPath: '/users/$login'
      preLoaderRoute: typeof UsersLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/create': {
      id: '/tournaments/create'
      path: '/tournaments/create'
      fullPath: '/tournaments/create'
      preLoaderRoute: typeof TournamentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id/organizer': {
      id: '/tournaments/$id/organizer'
      path: '/organizer'
      fullPath: '/tournaments/$id/organizer'
      preLoaderRoute: typeof TournamentsIdOrganizerRouteImport
      parentRoute: typeof TournamentsIdRoute
    }
    '/tournaments/$id/bracket': {
      id: '/tournaments/$id/bracket'
      path: '/bracket'
      fullPath: '/tournaments/$id/bracket'
      preLoaderRoute: typeof TournamentsIdBracketRouteImport
      parentRoute: typeof TournamentsIdRoute
    }
    '/tournaments/$id/groups/$groupId': {
      id: '/tournaments/$id/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/tournaments/$id/groups/$groupId'
      preLoaderRoute: typeof TournamentsIdGroupsGroupIdRouteImport
      parentRoute: typeof TournamentsIdRoute
    }
  }
}

interface TournamentsIdRouteChildren {
  TournamentsIdBracketRoute: typeof TournamentsIdBracketRoute
  TournamentsIdOrganizerRoute: typeof TournamentsIdOrganizerRoute
  TournamentsIdGroupsGroupIdRoute: typeof TournamentsIdGroupsGroupIdRoute
}

const TournamentsIdRouteChildren: TournamentsIdRouteChildren = {
  TournamentsIdBracketRoute: TournamentsIdBracketRoute,
  TournamentsIdOrganizerRoute: TournamentsIdOrganizerRoute,
  TournamentsIdGroupsGroupIdRoute: TournamentsIdGroupsGroupIdRoute,
}

const TournamentsIdRouteWithChildren = TournamentsIdRoute._addFileChildren(
  TournamentsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ProfileRoute: ProfileRoute,
  MatchesIdRoute: MatchesIdRoute,
  TournamentsIdRoute: TournamentsIdRouteWithChildren,
  TournamentsCreateRoute: TournamentsCreateRoute,
  UsersLoginRoute: UsersLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
